# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/hello-nbdev',
                'doc_host': 'https://akshatgoel92.github.io',
                'git_url': 'https://github.com/akshatgoel92/hello-nbdev',
                'lib_path': 'hello_nbdev'},
  'syms': { 'hello_nbdev.core': { 'hello_nbdev.core.HelloSayer': ('core.html#hellosayer', 'hello_nbdev/core.py'),
                                  'hello_nbdev.core.HelloSayer.__init__': ('core.html#hellosayer.__init__', 'hello_nbdev/core.py'),
                                  'hello_nbdev.core.HelloSayer.say': ('core.html#hellosayer.say', 'hello_nbdev/core.py'),
                                  'hello_nbdev.core.hello_name': ('core.html#hello_name', 'hello_nbdev/core.py'),
                                  'hello_nbdev.core.hello_world': ('core.html#hello_world', 'hello_nbdev/core.py')}}}
