# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['hello_world', 'hello_name']

# %% ../nbs/00_core.ipynb 3
def hello_world():
    """
    Say hello!
    """
    print("Hello world!")

# %% ../nbs/00_core.ipynb 4
def hello_name(name):
    """
    Say hello to somebody!
    """
    print(f"Hello {name}!")

# %% ../nbs/00_core.ipynb 5
# Tests
assert hello_world() == None
assert hello_name("Akshat") == None
