# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['hello_world', 'hello_name', 'HelloSayer']

# %% ../nbs/00_core.ipynb 3
def hello_world():
    """
    Say hello!
    """
    print("Hello world!")

# %% ../nbs/00_core.ipynb 4
def hello_name(name):
    """
    Say hello to somebody!
    """
    print(f"Hello {name}!")

# %% ../nbs/00_core.ipynb 5
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): 
        self.to = to
    
    def say(self):
        "Do the saying"
        return say_hello(self.to)

# %% ../nbs/00_core.ipynb 6
# Tests
assert hello_world() == None
assert hello_name("Akshat") == None
